[build]
  command = "pnpm build"
  publish = "dist"


[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/home"
  to = "/.netlify/functions/entry"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/entry"
  status = 200