[build]
  command = "pnpm build"
  publish = "dist/"
  functions = ".netlify/functions"

  [functions]
  node_bundler = "esbuild"

  [images]
  remote_images = [
       "https:\\/\\/i\\.imgur\\.com\\/.*",
        "https:\\/\\/imgur\\.com\\/.*"
  ]

[dev]
 command = "pnpm dev"
 port = 8888
 targetPort = 4321
 autoLaunch = true
 framework = "#custom"

[[redirects]]
  from = "/home"
  to = "/.netlify/build/entry"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/build/entry"
  status = 200