[build]
  command = "pnpm build"
  publish = "dist/"


[[redirects]]
  from = "/home"
  to = "/.netlify/build/entry"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/build/entry"
  status = 200