[build]
  command = "pnpm build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/home"
  to = "/.netlify/functions/entry"
  status = 302

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/entry"
  status = 200